import { CKANDataset } from "./types";

// Seed datasets based on real Berlin Open Data entries.
// Used as fallback when the live CKAN API is unreachable.
export const SEED_DATASETS: CKANDataset[] = [
  {
    id: "seed-001",
    name: "einwohnerinnen-und-einwohner-berlin-lor-planungsräumen",
    title: "Einwohnerinnen und Einwohner in Berlin (LOR-Planungsräume)",
    notes:
      "Angaben zu Einwohnerinnen und Einwohnern in Berlin, gegliedert nach LOR-Planungsräumen. Der Datensatz umfasst demografische Grunddaten wie Alter, Geschlecht und Staatsangehörigkeit auf kleinräumiger Ebene. Die Daten werden regelmässig aktualisiert und bieten eine detaillierte Uebersicht über die Bevölkerungsstruktur der Hauptstadt.",
    author: "Amt für Statistik Berlin-Brandenburg",
    author_email: "info@statistik-bbb.de",
    maintainer: "Open Data Berlin",
    maintainer_email: "opendata@berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2018-03-15T10:00:00.000000",
    metadata_modified: "2026-01-10T08:30:00.000000",
    num_resources: 4,
    num_tags: 6,
    tags: [
      { name: "bevölkerung" },
      { name: "demografie" },
      { name: "einwohner" },
      { name: "lor" },
      { name: "planungsraum" },
      { name: "statistik" },
    ],
    groups: [{ name: "demographie", title: "Demografie" }],
    organization: {
      name: "statistik-berlin-brandenburg",
      title: "Amt für Statistik Berlin-Brandenburg",
    },
    resources: [
      {
        id: "r001a",
        name: "Einwohner 2024 CSV",
        format: "CSV",
        url: "",
        created: "2024-06-01",
        last_modified: "2025-12-01",
      },
      {
        id: "r001b",
        name: "Einwohner 2024 GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2024-06-01",
        last_modified: "2025-12-01",
      },
      {
        id: "r001c",
        name: "Einwohner 2023 CSV",
        format: "CSV",
        url: "",
        created: "2023-06-01",
        last_modified: "2024-06-01",
      },
      {
        id: "r001d",
        name: "Metadaten PDF",
        format: "PDF",
        url: "",
        created: "2018-03-15",
        last_modified: "2024-06-01",
      },
    ],
  },
  {
    id: "seed-002",
    name: "fahrraddiebstahl-berlin",
    title: "Fahrraddiebstahl in Berlin",
    notes:
      "Gemeldete Fahrraddiebstähle in Berlin nach LOR-Planungsräumen. Enthält Informationen zu Tatort, Tatzeitraum, Schadenshöhe und Art des gestohlenen Fahrrads. Die Daten werden von der Berliner Polizei bereitgestellt und jährlich aktualisiert.",
    author: "Polizei Berlin",
    author_email: "",
    maintainer: "Polizei Berlin",
    maintainer_email: "",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2019-07-01T12:00:00.000000",
    metadata_modified: "2025-11-15T09:00:00.000000",
    num_resources: 2,
    num_tags: 4,
    tags: [
      { name: "kriminalität" },
      { name: "fahrrad" },
      { name: "diebstahl" },
      { name: "polizei" },
    ],
    groups: [
      { name: "öffentliche-sicherheit", title: "Öffentliche Sicherheit" },
    ],
    organization: { name: "polizei-berlin", title: "Polizei Berlin" },
    resources: [
      {
        id: "r002a",
        name: "Fahrraddiebstahl 2024 CSV",
        format: "CSV",
        url: "",
        created: "2024-03-01",
        last_modified: "2025-11-01",
      },
      {
        id: "r002b",
        name: "Fahrraddiebstahl 2024 XLSX",
        format: "XLSX",
        url: "",
        created: "2024-03-01",
        last_modified: "2025-11-01",
      },
    ],
  },
  {
    id: "seed-003",
    name: "berliner-strassenbäume",
    title: "Baumkataster Berlin - Strassenbäume",
    notes:
      "Verzeichnis aller Strassenbäume in Berlin mit Standort, Baumart, Pflanzjahr, Stammumfang, Kronendurchmesser und Baumhöhe. Das Kataster umfasst über 430.000 Bäume und wird regelmässig gepflegt. Der Datensatz ist ein zentrales Werkzeug für die Stadtplanung und das Umweltmonitoring.",
    author: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    author_email: "post@senmvku.berlin.de",
    maintainer: "Geoinformation Berlin",
    maintainer_email: "gdi@senmvku.berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2017-05-20T08:00:00.000000",
    metadata_modified: "2026-03-01T10:00:00.000000",
    num_resources: 5,
    num_tags: 7,
    tags: [
      { name: "bäume" },
      { name: "strassenbäume" },
      { name: "kataster" },
      { name: "umwelt" },
      { name: "grün" },
      { name: "stadtplanung" },
      { name: "geodaten" },
    ],
    groups: [{ name: "umwelt-und-klima", title: "Umwelt und Klima" }],
    organization: {
      name: "senmvku",
      title: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    },
    resources: [
      {
        id: "r003a",
        name: "Baumkataster GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2023-01-01",
        last_modified: "2026-03-01",
      },
      {
        id: "r003b",
        name: "Baumkataster CSV",
        format: "CSV",
        url: "",
        created: "2023-01-01",
        last_modified: "2026-03-01",
      },
      {
        id: "r003c",
        name: "Baumkataster WFS",
        format: "WFS",
        url: "",
        created: "2019-01-01",
        last_modified: "2026-03-01",
      },
      {
        id: "r003d",
        name: "Baumkataster SHP",
        format: "ZIP",
        url: "",
        created: "2019-01-01",
        last_modified: "2025-01-01",
      },
      {
        id: "r003e",
        name: "Dokumentation PDF",
        format: "PDF",
        url: "",
        created: "2017-05-20",
        last_modified: "2023-01-01",
      },
    ],
  },
  {
    id: "seed-004",
    name: "ladestationen-elektrofahrzeuge-berlin",
    title: "Ladestationen für Elektrofahrzeuge in Berlin",
    notes:
      "Standorte aller öffentlich zugänglichen Ladestationen für Elektrofahrzeuge in Berlin mit Angaben zu Betreiber, Steckertyp, Ladeleistung und Verfügbarkeit.",
    author: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    author_email: "post@senmvku.berlin.de",
    maintainer: "Open Data Berlin",
    maintainer_email: "opendata@berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2020-01-15T10:00:00.000000",
    metadata_modified: "2026-04-20T14:00:00.000000",
    num_resources: 3,
    num_tags: 5,
    tags: [
      { name: "elektromobilität" },
      { name: "ladestation" },
      { name: "verkehr" },
      { name: "mobil" },
      { name: "energie" },
    ],
    groups: [{ name: "verkehr", title: "Verkehr" }],
    organization: {
      name: "senmvku",
      title: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    },
    resources: [
      {
        id: "r004a",
        name: "Ladestationen JSON",
        format: "JSON",
        url: "",
        created: "2024-01-01",
        last_modified: "2026-04-20",
      },
      {
        id: "r004b",
        name: "Ladestationen CSV",
        format: "CSV",
        url: "",
        created: "2024-01-01",
        last_modified: "2026-04-20",
      },
      {
        id: "r004c",
        name: "Ladestationen GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2024-01-01",
        last_modified: "2026-04-20",
      },
    ],
  },
  {
    id: "seed-005",
    name: "wahlbezirke-berlin",
    title: "Wahlbezirke Berlin - Geometrien und Ergebnisse",
    notes:
      "Geometrien der Wahlbezirke in Berlin sowie die zugehörigen Wahlergebnisse der letzten Bundestags-, Abgeordnetenhaus- und Bezirkswahlen. Enthält Stimmanteile, Wahlbeteiligung und Sitzverteilung auf Wahlbezirksebene. Maschinenlesbar als RDF Linked Data verfügbar.",
    author: "Landeswahlleiter Berlin",
    author_email: "wahlen@berlin.de",
    maintainer: "Landeswahlleiter Berlin",
    maintainer_email: "wahlen@berlin.de",
    license_title: "Creative Commons Zero",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    url: "",
    metadata_created: "2016-09-01T08:00:00.000000",
    metadata_modified: "2025-06-01T10:00:00.000000",
    num_resources: 4,
    num_tags: 5,
    tags: [
      { name: "wahlen" },
      { name: "wahlbezirke" },
      { name: "politik" },
      { name: "demokratie" },
      { name: "ergebnisse" },
    ],
    groups: [{ name: "verwaltung", title: "Verwaltung" }],
    organization: {
      name: "landeswahlleiter",
      title: "Landeswahlleiter Berlin",
    },
    resources: [
      {
        id: "r005a",
        name: "Wahlergebnisse RDF",
        format: "RDF",
        url: "",
        created: "2023-03-01",
        last_modified: "2025-06-01",
      },
      {
        id: "r005b",
        name: "Wahlergebnisse JSON-LD",
        format: "JSON-LD",
        url: "",
        created: "2023-03-01",
        last_modified: "2025-06-01",
      },
      {
        id: "r005c",
        name: "Wahlbezirke GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2023-03-01",
        last_modified: "2025-06-01",
      },
      {
        id: "r005d",
        name: "Wahlergebnisse CSV",
        format: "CSV",
        url: "",
        created: "2023-03-01",
        last_modified: "2025-06-01",
      },
    ],
  },
  {
    id: "seed-006",
    name: "spielplätze-berlin",
    title: "Spielplätze in Berlin",
    notes:
      "Standorte und Ausstattung öffentlicher Spielplätze in Berlin. Enthält Informationen zur Grösse, zum Zustand und zu vorhandenen Spielgeräten.",
    author: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    author_email: "",
    maintainer: "",
    maintainer_email: "",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2021-06-01T10:00:00.000000",
    metadata_modified: "2024-09-15T10:00:00.000000",
    num_resources: 1,
    num_tags: 3,
    tags: [
      { name: "spielplätze" },
      { name: "kinder" },
      { name: "infrastruktur" },
    ],
    groups: [{ name: "infrastruktur", title: "Infrastruktur" }],
    organization: {
      name: "sensbw",
      title: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    },
    resources: [
      {
        id: "r006a",
        name: "Spielplätze XLS",
        format: "XLS",
        url: "",
        created: "2024-01-01",
        last_modified: "2024-09-15",
      },
    ],
  },
  {
    id: "seed-007",
    name: "berliner-badestellen-wasserqualität",
    title: "Berliner Badestellen - Wasserqualität",
    notes:
      "Aktülle Wasserqualitätsdaten der Berliner Badestellen. Enthält Messwerte zu E.coli, Enterokokken, Sichttiefe und Wassertemperatur. Die Daten werden während der Badesaison wöchentlich aktualisiert und umfassen alle offiziellen EU-Badestellen in Berlin. Detaillierte Dokumentation und historische Vergleichsdaten sind ebenfalls enthalten.",
    author: "Landesamt für Gesundheit und Soziales",
    author_email: "lageso@lageso.berlin.de",
    maintainer: "LAGeSo",
    maintainer_email: "lageso@lageso.berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2015-04-01T08:00:00.000000",
    metadata_modified: "2026-05-01T10:00:00.000000",
    num_resources: 3,
    num_tags: 6,
    tags: [
      { name: "badestellen" },
      { name: "wasserqualität" },
      { name: "gesundheit" },
      { name: "umwelt" },
      { name: "badesaison" },
      { name: "messwerte" },
    ],
    groups: [{ name: "gesundheit", title: "Gesundheit" }],
    organization: {
      name: "lageso",
      title: "Landesamt für Gesundheit und Soziales",
    },
    resources: [
      {
        id: "r007a",
        name: "Badegewässer JSON",
        format: "JSON",
        url: "",
        created: "2023-05-01",
        last_modified: "2026-05-01",
      },
      {
        id: "r007b",
        name: "Badegewässer CSV",
        format: "CSV",
        url: "",
        created: "2023-05-01",
        last_modified: "2026-05-01",
      },
      {
        id: "r007c",
        name: "Historische Daten CSV",
        format: "CSV",
        url: "",
        created: "2015-04-01",
        last_modified: "2025-10-01",
      },
    ],
  },
  {
    id: "seed-008",
    name: "berlin-lor-bezirksregionen",
    title: "Lebensweltlich orientierte Räume (LOR) - Bezirksregionen",
    notes:
      "Geodaten der lebensweltlich orientierten Räume (LOR) in Berlin auf Bezirksregionsebene. Die LOR bilden die Grundlage für die kleinräumige Planung und Statistik in Berlin.",
    author: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    author_email: "post@sensbw.berlin.de",
    maintainer: "FIS-Broker",
    maintainer_email: "fisbroker@sensbw.berlin.de",
    license_title: "Datenlizenz Deutschland - Namensnennung",
    license_url: "https://www.govdata.de/dl-de/by-2-0",
    url: "",
    metadata_created: "2014-01-01T08:00:00.000000",
    metadata_modified: "2025-03-01T10:00:00.000000",
    num_resources: 3,
    num_tags: 4,
    tags: [
      { name: "lor" },
      { name: "bezirksregionen" },
      { name: "geodaten" },
      { name: "planung" },
    ],
    groups: [
      {
        name: "geographie-und-stadtplanung",
        title: "Geographie und Stadtplanung",
      },
    ],
    organization: {
      name: "sensbw",
      title: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    },
    resources: [
      {
        id: "r008a",
        name: "LOR Bezirksregionen GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2023-01-01",
        last_modified: "2025-03-01",
      },
      {
        id: "r008b",
        name: "LOR Bezirksregionen WFS",
        format: "WFS",
        url: "",
        created: "2020-01-01",
        last_modified: "2025-03-01",
      },
      {
        id: "r008c",
        name: "LOR Dokumentation PDF",
        format: "PDF",
        url: "",
        created: "2014-01-01",
        last_modified: "2023-06-01",
      },
    ],
  },
  {
    id: "seed-009",
    name: "schulen-berlin",
    title: "Schulverzeichnis Berlin",
    notes:
      "Verzeichnis aller allgemeinbildenden und beruflichen Schulen in Berlin mit Adresse, Schulart, Trägerschaft, Schüler- und Lehrerzahlen sowie Kontaktdaten. Das Verzeichnis wird vom Amt für Statistik gepflegt.",
    author: "Senatsverwaltung für Bildung, Jugend und Familie",
    author_email: "post@senbjf.berlin.de",
    maintainer: "Open Data Berlin",
    maintainer_email: "opendata@berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2019-08-01T10:00:00.000000",
    metadata_modified: "2025-09-01T10:00:00.000000",
    num_resources: 2,
    num_tags: 4,
    tags: [
      { name: "schule" },
      { name: "bildung" },
      { name: "verzeichnis" },
      { name: "infrastruktur" },
    ],
    groups: [{ name: "bildung", title: "Bildung" }],
    organization: {
      name: "senbjf",
      title: "Senatsverwaltung für Bildung, Jugend und Familie",
    },
    resources: [
      {
        id: "r009a",
        name: "Schulverzeichnis CSV",
        format: "CSV",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-09-01",
      },
      {
        id: "r009b",
        name: "Schulverzeichnis XLSX",
        format: "XLSX",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-09-01",
      },
    ],
  },
  {
    id: "seed-010",
    name: "luftqualität-berlin-messstationen",
    title: "Luftqualität Berlin - Stundenwerte Messstationen",
    notes:
      "Stundenwerte der Luftqualitätsmessstationen in Berlin. Messwerte für Stickstoffdioxid (NO2), Feinstaub (PM10, PM2.5), Ozon (O3) und weitere Schadstoffe. Die Daten werden automatisch erfasst und stündlich aktualisiert. Umfangreiche Zeitreihen seit 2010 verfügbar.",
    author: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    author_email: "post@senmvku.berlin.de",
    maintainer: "Berliner Luftgüte Messnetz (BLUME)",
    maintainer_email: "blume@senmvku.berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2016-01-01T08:00:00.000000",
    metadata_modified: "2026-05-20T12:00:00.000000",
    num_resources: 6,
    num_tags: 7,
    tags: [
      { name: "luftqualität" },
      { name: "umwelt" },
      { name: "messdaten" },
      { name: "no2" },
      { name: "feinstaub" },
      { name: "klima" },
      { name: "zeitreihen" },
    ],
    groups: [{ name: "umwelt-und-klima", title: "Umwelt und Klima" }],
    organization: {
      name: "senmvku",
      title: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    },
    resources: [
      {
        id: "r010a",
        name: "Stundenwerte JSON API",
        format: "API",
        url: "",
        created: "2020-01-01",
        last_modified: "2026-05-20",
      },
      {
        id: "r010b",
        name: "Stundenwerte CSV",
        format: "CSV",
        url: "",
        created: "2020-01-01",
        last_modified: "2026-05-20",
      },
      {
        id: "r010c",
        name: "Tageswerte CSV",
        format: "CSV",
        url: "",
        created: "2020-01-01",
        last_modified: "2026-05-20",
      },
      {
        id: "r010d",
        name: "Monatsmittel CSV",
        format: "CSV",
        url: "",
        created: "2016-01-01",
        last_modified: "2026-05-20",
      },
      {
        id: "r010e",
        name: "Stationen GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2020-01-01",
        last_modified: "2025-01-01",
      },
      {
        id: "r010f",
        name: "Dokumentation PDF",
        format: "PDF",
        url: "",
        created: "2016-01-01",
        last_modified: "2023-06-01",
      },
    ],
  },
  {
    id: "seed-011",
    name: "berlin-haushalt-einnahmen-ausgaben",
    title: "Berliner Haushalt - Einnahmen und Ausgaben",
    notes:
      "Detaillierte Aufstellung des Berliner Landeshaushalts mit Einnahmen und Ausgaben nach Einzelplänen, Kapiteln und Titeln. Der Datensatz ermöglicht Transparenz über die Verwendung öffentlicher Mittel.",
    author: "Senatsverwaltung für Finanzen",
    author_email: "post@senfin.berlin.de",
    maintainer: "",
    maintainer_email: "",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2020-03-01T10:00:00.000000",
    metadata_modified: "2025-04-01T10:00:00.000000",
    num_resources: 1,
    num_tags: 3,
    tags: [{ name: "haushalt" }, { name: "finanzen" }, { name: "wirtschaft" }],
    groups: [{ name: "haushalt-und-steürn", title: "Haushalt und Steürn" }],
    organization: { name: "senfin", title: "Senatsverwaltung für Finanzen" },
    resources: [
      {
        id: "r011a",
        name: "Haushalt PDF",
        format: "PDF",
        url: "",
        created: "2025-01-01",
        last_modified: "2025-04-01",
      },
    ],
  },
  {
    id: "seed-012",
    name: "berlin-wlan-standorte",
    title: "Öffentliche WLAN-Standorte in Berlin (Free WiFi)",
    notes:
      "Standorte des kostenlosen öffentlichen WLAN-Angebots in Berlin. Enthält Informationen zum Provider, zur Abdeckung und zur Verfügbarkeit der Hotspots.",
    author: "Senatskanzlei Berlin",
    author_email: "",
    maintainer: "Open Data Berlin",
    maintainer_email: "opendata@berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2019-11-01T10:00:00.000000",
    metadata_modified: "2025-08-01T10:00:00.000000",
    num_resources: 2,
    num_tags: 4,
    tags: [
      { name: "wlan" },
      { name: "wifi" },
      { name: "infrastruktur" },
      { name: "digital" },
    ],
    groups: [{ name: "infrastruktur", title: "Infrastruktur" }],
    organization: { name: "senatskanzlei", title: "Senatskanzlei Berlin" },
    resources: [
      {
        id: "r012a",
        name: "WLAN Standorte JSON",
        format: "JSON",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-08-01",
      },
      {
        id: "r012b",
        name: "WLAN Standorte CSV",
        format: "CSV",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-08-01",
      },
    ],
  },
  {
    id: "seed-013",
    name: "verkehrsunfälle-berlin",
    title: "Verkehrsunfälle in Berlin",
    notes:
      "Verkehrsunfalldaten der Berliner Polizei mit Angaben zu Unfallort, Unfalltyp, Beteiligte, Verletzte und Sachschäden. Die Daten werden jährlich veröffentlicht und umfassen georeferenzierte Informationen zu jedem Unfall. Der Datensatz ist besonders umfangreich und enthält detaillierte Klassifikationen nach Unfallschwere und beteiligten Verkehrsmitteln.",
    author: "Polizei Berlin",
    author_email: "polizei@polizei.berlin.de",
    maintainer: "Polizei Berlin",
    maintainer_email: "polizei@polizei.berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2018-01-01T08:00:00.000000",
    metadata_modified: "2025-07-01T10:00:00.000000",
    num_resources: 3,
    num_tags: 5,
    tags: [
      { name: "verkehr" },
      { name: "unfälle" },
      { name: "polizei" },
      { name: "sicherheit" },
      { name: "geodaten" },
    ],
    groups: [{ name: "verkehr", title: "Verkehr" }],
    organization: { name: "polizei-berlin", title: "Polizei Berlin" },
    resources: [
      {
        id: "r013a",
        name: "Unfälle GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-07-01",
      },
      {
        id: "r013b",
        name: "Unfälle CSV",
        format: "CSV",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-07-01",
      },
      {
        id: "r013c",
        name: "Unfallstatistik XLSX",
        format: "XLSX",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-07-01",
      },
    ],
  },
  {
    id: "seed-014",
    name: "solarpotenzial-berlin",
    title: "Solarpotenzial der Berliner Dachflächen",
    notes:
      "Analyse des Solarpotenzials aller Dachflächen in Berlin basierend auf Laserscanning-Daten. Enthält Informationen zur Eignung für Photovoltaik- und Solarthermieanlagen, inklusive erwarteter Ertragswerte und CO2-Einsparungen. Der Datensatz deckt sämtliche Gebäude Berlins ab.",
    author: "Senatsverwaltung für Wirtschaft, Energie und Betriebe",
    author_email: "post@senweb.berlin.de",
    maintainer: "Berliner Energieagentur",
    maintainer_email: "info@berliner-e-agentur.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2017-10-01T08:00:00.000000",
    metadata_modified: "2024-12-01T10:00:00.000000",
    num_resources: 2,
    num_tags: 5,
    tags: [
      { name: "solar" },
      { name: "energie" },
      { name: "klima" },
      { name: "photovoltaik" },
      { name: "dachflächen" },
    ],
    groups: [{ name: "umwelt-und-klima", title: "Umwelt und Klima" }],
    organization: {
      name: "senweb",
      title: "Senatsverwaltung für Wirtschaft, Energie und Betriebe",
    },
    resources: [
      {
        id: "r014a",
        name: "Solarpotenzial WMS",
        format: "WMS",
        url: "",
        created: "2023-01-01",
        last_modified: "2024-12-01",
      },
      {
        id: "r014b",
        name: "Zusammenfassung PDF",
        format: "PDF",
        url: "",
        created: "2017-10-01",
        last_modified: "2024-12-01",
      },
    ],
  },
  {
    id: "seed-015",
    name: "bibliotheken-berlin",
    title: "Öffentliche Bibliotheken in Berlin",
    notes:
      "Standorte und Oeffnungszeiten der öffentlichen Bibliotheken in Berlin, inklusive Medienbestand und Veranstaltungsprogramm.",
    author: "Verbund der Öffentlichen Bibliotheken Berlins",
    author_email: "",
    maintainer: "",
    maintainer_email: "",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2022-02-01T10:00:00.000000",
    metadata_modified: "2025-02-01T10:00:00.000000",
    num_resources: 1,
    num_tags: 2,
    tags: [{ name: "bibliotheken" }, { name: "kultur" }],
    groups: [{ name: "bildung", title: "Bildung" }],
    organization: {
      name: "vöbb",
      title: "Verbund der Öffentlichen Bibliotheken Berlins",
    },
    resources: [
      {
        id: "r015a",
        name: "Bibliotheken XLSX",
        format: "XLSX",
        url: "",
        created: "2025-01-01",
        last_modified: "2025-02-01",
      },
    ],
  },
  {
    id: "seed-016",
    name: "berlin-kitas-standorte",
    title: "Kindertagesstätten (Kitas) in Berlin",
    notes:
      "Verzeichnis aller Kindertagesstätten in Berlin mit Standort, Träger, Platzzahl und pädagogischem Konzept. Der Datensatz umfasst sowohl städtische als auch freie Träger und wird halbjährlich aktualisiert. Detaillierte Informationen zu Betreuungsschlüssel und Oeffnungszeiten sind enthalten.",
    author: "Senatsverwaltung für Bildung, Jugend und Familie",
    author_email: "post@senbjf.berlin.de",
    maintainer: "Open Data Berlin",
    maintainer_email: "opendata@berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2018-06-01T10:00:00.000000",
    metadata_modified: "2026-02-01T10:00:00.000000",
    num_resources: 3,
    num_tags: 4,
    tags: [
      { name: "kita" },
      { name: "kinderbetreuung" },
      { name: "bildung" },
      { name: "soziales" },
    ],
    groups: [{ name: "bildung", title: "Bildung" }],
    organization: {
      name: "senbjf",
      title: "Senatsverwaltung für Bildung, Jugend und Familie",
    },
    resources: [
      {
        id: "r016a",
        name: "Kitas GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2024-01-01",
        last_modified: "2026-02-01",
      },
      {
        id: "r016b",
        name: "Kitas CSV",
        format: "CSV",
        url: "",
        created: "2024-01-01",
        last_modified: "2026-02-01",
      },
      {
        id: "r016c",
        name: "Kitas JSON",
        format: "JSON",
        url: "",
        created: "2024-01-01",
        last_modified: "2026-02-01",
      },
    ],
  },
  {
    id: "seed-017",
    name: "alkis-berlin-gebäude",
    title: "ALKIS Berlin - Gebäude und Bauwerke",
    notes:
      "Gebäude- und Bauwerksdaten aus dem Amtlichen Liegenschaftskatasterinformationssystem (ALKIS) für Berlin. Enthält Grundrisse, Nutzungsarten, Geschosszahlen und Baujahr aller Gebäude.",
    author: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    author_email: "post@sensbw.berlin.de",
    maintainer: "Geoinformation Berlin",
    maintainer_email: "gdi@sensbw.berlin.de",
    license_title: "Datenlizenz Deutschland - Namensnennung",
    license_url: "https://www.govdata.de/dl-de/by-2-0",
    url: "",
    metadata_created: "2015-01-01T08:00:00.000000",
    metadata_modified: "2025-12-01T10:00:00.000000",
    num_resources: 2,
    num_tags: 3,
    tags: [{ name: "alkis" }, { name: "gebäude" }, { name: "kataster" }],
    groups: [
      {
        name: "geographie-und-stadtplanung",
        title: "Geographie und Stadtplanung",
      },
    ],
    organization: {
      name: "sensbw",
      title: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    },
    resources: [
      {
        id: "r017a",
        name: "ALKIS Gebäude WFS",
        format: "WFS",
        url: "",
        created: "2020-01-01",
        last_modified: "2025-12-01",
      },
      {
        id: "r017b",
        name: "ALKIS Gebäude WMS",
        format: "WMS",
        url: "",
        created: "2020-01-01",
        last_modified: "2025-12-01",
      },
    ],
  },
  {
    id: "seed-018",
    name: "denkmalliste-berlin",
    title: "Denkmalliste Berlin",
    notes:
      "Liste der Baudenkmale, Gartendenkmale und Bodendenkmale in Berlin. Enthält Informationen zur Adresse, Denkmalart, Baujahr und kurze Beschreibung der denkmalgeschützten Objekte.",
    author: "Landesdenkmalamt Berlin",
    author_email: "post@lda.berlin.de",
    maintainer: "Landesdenkmalamt Berlin",
    maintainer_email: "post@lda.berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2017-03-01T10:00:00.000000",
    metadata_modified: "2025-10-01T10:00:00.000000",
    num_resources: 2,
    num_tags: 4,
    tags: [
      { name: "denkmal" },
      { name: "denkmalschutz" },
      { name: "kultur" },
      { name: "architektur" },
    ],
    groups: [{ name: "kultur", title: "Kultur und Freizeit" }],
    organization: { name: "lda", title: "Landesdenkmalamt Berlin" },
    resources: [
      {
        id: "r018a",
        name: "Denkmalliste CSV",
        format: "CSV",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-10-01",
      },
      {
        id: "r018b",
        name: "Denkmalliste GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2024-01-01",
        last_modified: "2025-10-01",
      },
    ],
  },
  {
    id: "seed-019",
    name: "berlin-lor-sozialstrukturatlas",
    title: "Sozialstrukturatlas Berlin (LOR)",
    notes:
      "Der Sozialstrukturatlas bildet soziale, demografische und gesundheitliche Indikatoren auf LOR-Ebene ab. Enthält Indizes für soziale Benachteiligung, Arbeitslosigkeit, Transferleistungen und Gesundheitsindikatoren.",
    author: "Senatsverwaltung für Wissenschaft, Gesundheit und Pflege",
    author_email: "",
    maintainer: "Open Data Berlin",
    maintainer_email: "opendata@berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2013-01-01T08:00:00.000000",
    metadata_modified: "2024-06-01T10:00:00.000000",
    num_resources: 1,
    num_tags: 5,
    tags: [
      { name: "sozialstruktur" },
      { name: "bevölkerung" },
      { name: "gesundheit" },
      { name: "lor" },
      { name: "soziales" },
    ],
    groups: [{ name: "demographie", title: "Demografie" }],
    organization: {
      name: "senwgp",
      title: "Senatsverwaltung für Wissenschaft, Gesundheit und Pflege",
    },
    resources: [
      {
        id: "r019a",
        name: "Sozialstrukturatlas PDF",
        format: "PDF",
        url: "",
        created: "2024-01-01",
        last_modified: "2024-06-01",
      },
    ],
  },
  {
    id: "seed-020",
    name: "berlin-öpnv-haltestellen",
    title: "OEPNV-Haltestellen Berlin (BVG und S-Bahn)",
    notes:
      "Standorte aller Haltestellen des öffentlichen Nahverkehrs in Berlin inklusive U-Bahn, S-Bahn, Tram, Bus und Fähre. Enthält barrierefreie Zugangsinformationen, Umsteigeverbindungen und Bedienungshäufigkeit. Als Linked Open Data verfügbar mit Verlinkung zu europäischen Verkehrsdaten.",
    author: "Berliner Verkehrsbetriebe (BVG)",
    author_email: "info@bvg.de",
    maintainer: "BVG Open Data",
    maintainer_email: "opendata@bvg.de",
    license_title: "Creative Commons Zero",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    url: "",
    metadata_created: "2014-06-01T10:00:00.000000",
    metadata_modified: "2026-05-10T10:00:00.000000",
    num_resources: 5,
    num_tags: 6,
    tags: [
      { name: "öpnv" },
      { name: "haltestellen" },
      { name: "verkehr" },
      { name: "bvg" },
      { name: "mobil" },
      { name: "barrierefreiheit" },
    ],
    groups: [{ name: "verkehr", title: "Verkehr" }],
    organization: { name: "bvg", title: "Berliner Verkehrsbetriebe (BVG)" },
    resources: [
      {
        id: "r020a",
        name: "Haltestellen RDF/Turtle",
        format: "Turtle",
        url: "",
        created: "2023-01-01",
        last_modified: "2026-05-10",
      },
      {
        id: "r020b",
        name: "Haltestellen JSON-LD",
        format: "JSON-LD",
        url: "",
        created: "2023-01-01",
        last_modified: "2026-05-10",
      },
      {
        id: "r020c",
        name: "Haltestellen GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2023-01-01",
        last_modified: "2026-05-10",
      },
      {
        id: "r020d",
        name: "Haltestellen CSV",
        format: "CSV",
        url: "",
        created: "2020-01-01",
        last_modified: "2026-05-10",
      },
      {
        id: "r020e",
        name: "Fahrplandaten GTFS",
        format: "ZIP",
        url: "",
        created: "2020-01-01",
        last_modified: "2026-05-01",
      },
    ],
  },
  {
    id: "seed-021",
    name: "berlin-mietspiegel",
    title: "Berliner Mietspiegel - Mietrichtwerte",
    notes:
      "Mietrichtwerte des Berliner Mietspiegels nach Wohnlage und Baualtersklasse. Der Mietspiegel ist ein wichtiges Instrument für Mieter und Vermieter zur Orientierung bei Mietpreisen.",
    author: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    author_email: "post@sensbw.berlin.de",
    maintainer: "",
    maintainer_email: "",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2019-06-01T10:00:00.000000",
    metadata_modified: "2025-05-01T10:00:00.000000",
    num_resources: 2,
    num_tags: 3,
    tags: [{ name: "mietspiegel" }, { name: "wohnen" }, { name: "miete" }],
    groups: [{ name: "wohnen", title: "Wohnen und Immobilien" }],
    organization: {
      name: "sensbw",
      title: "Senatsverwaltung für Stadtentwicklung, Baün und Wohnen",
    },
    resources: [
      {
        id: "r021a",
        name: "Mietspiegel PDF",
        format: "PDF",
        url: "",
        created: "2025-01-01",
        last_modified: "2025-05-01",
      },
      {
        id: "r021b",
        name: "Mietrichtwerte CSV",
        format: "CSV",
        url: "",
        created: "2025-01-01",
        last_modified: "2025-05-01",
      },
    ],
  },
  {
    id: "seed-022",
    name: "berlin-gewerbeanmeldungen",
    title: "Gewerbeanmeldungen in Berlin",
    notes:
      "Statistik der Gewerbeanmeldungen und -abmeldungen in Berlin nach Bezirken, Branchen und Rechtsformen.",
    author: "Amt für Statistik Berlin-Brandenburg",
    author_email: "info@statistik-bbb.de",
    maintainer: "Amt für Statistik Berlin-Brandenburg",
    maintainer_email: "info@statistik-bbb.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2020-09-01T10:00:00.000000",
    metadata_modified: "2025-12-01T10:00:00.000000",
    num_resources: 2,
    num_tags: 4,
    tags: [
      { name: "gewerbe" },
      { name: "wirtschaft" },
      { name: "arbeit" },
      { name: "unternehmen" },
    ],
    groups: [{ name: "wirtschaft", title: "Wirtschaft" }],
    organization: {
      name: "statistik-berlin-brandenburg",
      title: "Amt für Statistik Berlin-Brandenburg",
    },
    resources: [
      {
        id: "r022a",
        name: "Gewerbeanmeldungen CSV",
        format: "CSV",
        url: "",
        created: "2025-01-01",
        last_modified: "2025-12-01",
      },
      {
        id: "r022b",
        name: "Gewerbeanmeldungen XLSX",
        format: "XLSX",
        url: "",
        created: "2025-01-01",
        last_modified: "2025-12-01",
      },
    ],
  },
  {
    id: "seed-023",
    name: "berlin-stolpersteine",
    title: "Stolpersteine in Berlin",
    notes:
      "Standorte aller Stolpersteine des Künstlers Gunter Demnig in Berlin. Enthält biografische Informationen zu den Opfern des Nationalsozialismus, Verlegedatum und genaü GPS-Koordinaten.",
    author: "Koordinierungsstelle Stolpersteine Berlin",
    author_email: "",
    maintainer: "Open Data Berlin",
    maintainer_email: "opendata@berlin.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2020-11-01T10:00:00.000000",
    metadata_modified: "2026-01-15T10:00:00.000000",
    num_resources: 2,
    num_tags: 4,
    tags: [
      { name: "stolpersteine" },
      { name: "gedenken" },
      { name: "geschichte" },
      { name: "kultur" },
    ],
    groups: [{ name: "kultur", title: "Kultur und Freizeit" }],
    organization: {
      name: "stolpersteine-berlin",
      title: "Koordinierungsstelle Stolpersteine Berlin",
    },
    resources: [
      {
        id: "r023a",
        name: "Stolpersteine GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2025-01-01",
        last_modified: "2026-01-15",
      },
      {
        id: "r023b",
        name: "Stolpersteine CSV",
        format: "CSV",
        url: "",
        created: "2025-01-01",
        last_modified: "2026-01-15",
      },
    ],
  },
  {
    id: "seed-024",
    name: "grundwasserspiegel-berlin",
    title: "Grundwasserspiegel und Messstellen Berlin",
    notes:
      "Messdaten zum Grundwasserspiegel in Berlin von über 2.000 Messstellen. Enthält historische Zeitreihen, aktülle Pegelstände und hydrogeologische Kennwerte. Die Daten werden automatisiert erfasst und täglich aktualisiert.",
    author: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    author_email: "post@senmvku.berlin.de",
    maintainer: "Berliner Wasserbetriebe",
    maintainer_email: "info@bwb.de",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2016-06-01T08:00:00.000000",
    metadata_modified: "2026-05-15T10:00:00.000000",
    num_resources: 4,
    num_tags: 5,
    tags: [
      { name: "grundwasser" },
      { name: "umwelt" },
      { name: "messdaten" },
      { name: "wasser" },
      { name: "zeitreihen" },
    ],
    groups: [{ name: "umwelt-und-klima", title: "Umwelt und Klima" }],
    organization: {
      name: "senmvku",
      title: "Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt",
    },
    resources: [
      {
        id: "r024a",
        name: "Messstellen JSON API",
        format: "API",
        url: "",
        created: "2022-01-01",
        last_modified: "2026-05-15",
      },
      {
        id: "r024b",
        name: "Messstellen GeoJSON",
        format: "GeoJSON",
        url: "",
        created: "2022-01-01",
        last_modified: "2026-05-15",
      },
      {
        id: "r024c",
        name: "Pegelstände CSV",
        format: "CSV",
        url: "",
        created: "2016-06-01",
        last_modified: "2026-05-15",
      },
      {
        id: "r024d",
        name: "Dokumentation PDF",
        format: "PDF",
        url: "",
        created: "2016-06-01",
        last_modified: "2024-01-01",
      },
    ],
  },
  {
    id: "seed-025",
    name: "berlin-zukunftsorte",
    title: "Zukunftsorte Berlin - Technologie- und Innovationsstandorte",
    notes:
      "Die elf Zukunftsorte Berlins sind Standorte, an denen Wirtschaft, Wissenschaft und Technologie eng zusammenarbeiten. Der Datensatz enthält Standortinformationen und ansässige Unternehmen und Forschungseinrichtungen.",
    author: "Senatsverwaltung für Wirtschaft, Energie und Betriebe",
    author_email: "post@senweb.berlin.de",
    maintainer: "",
    maintainer_email: "",
    license_title: "Creative Commons Attribution",
    license_url: "https://creativecommons.org/licenses/by/4.0/",
    url: "",
    metadata_created: "2021-04-01T10:00:00.000000",
    metadata_modified: "2024-03-01T10:00:00.000000",
    num_resources: 1,
    num_tags: 3,
    tags: [
      { name: "innovation" },
      { name: "wirtschaft" },
      { name: "technologie" },
    ],
    groups: [{ name: "wirtschaft", title: "Wirtschaft" }],
    organization: {
      name: "senweb",
      title: "Senatsverwaltung für Wirtschaft, Energie und Betriebe",
    },
    resources: [
      {
        id: "r025a",
        name: "Zukunftsorte PDF",
        format: "PDF",
        url: "",
        created: "2024-01-01",
        last_modified: "2024-03-01",
      },
    ],
  },
];
